print("Hi!")
input("")
name=input("What is your name? ")
print(f"Nice to meet you {name}.")
print("How are you today?")
input("")
print("great!")
name=input("What is your age? ")
print(f"Thats nice {name} is a good age to be.")
name=input("What's your favorite color? ")
print(f"Oh cool {name} is cool. ")
print ("What's your favorite thing to do? ")
input("")
print("fun ")
print("What is your favorite food? ")
input("")
print("Wow that's interesting ")
input("")
print("ok goodbye")
print(r"___. ")
print(r"\_ |__ ___.__. ____  ")
print(r"| __ <   |  |/ __ \ ")
print(r"| \_\ \___  \  ___/ ")
print(r"|___  / ____|\___  >")
print(r"     \/\/         \/ ")
input("")