print("Hi!")
input("")
name=input("What is your name?")
print(f"Nice to meet you {name} I'm Sahasra.")
print("How are you today?")
input("")
print("That's great!")
name=input("What is your age?")
print(f"Thats nice i'm also {name}")
name=input("What's your favorite color")
print(f"Oh cool {name} is my favorite color aswell")